### ISSUE TITLE
question about this project

### ISSUE THREAD

**Issue by linearregression** [jonromero/ReplicationEngine#5]
Hi I have done a bit of digging around of the project and written with some unit tests.
So is this repo for demonstration only? 
I notice that a node reports itself as both master and slave in a cluster of one. 
Or a master trying to join its own cluster should be ignored instead of crashing

**Comment by jonromero** [comment]
Yeap, this is for demo but the basic concept works. I actually use it in another project. Good work btw!

Hm, yes in a cluster of one, the node should be only master.
